### ISSUE TITLE
Seleccionar sistema de configuración para migrar.

### ISSUE THREAD

**Issue by xihh87** [xihh87/cluster#4]
Si se va a realizar #2, se necesita seleccionar uno adecuado:

- [CFEngine](https://cfengine.com/ ), es el servicio que inició el campo, usa agentes escritos en C. Es el más ligero y [conceptualizó](https://www.amazon.com/Promise-Theory-Principles-Applications-Volume/dp/1495437779/ref=sr_1_3?ie=UTF8&qid=1391713533&sr=8-3&keywords=promise+theory ) [las promesas](http://markburgess.org/TIpromises.html ). Sin embargo parece que la curva de aprendizaje es difícil. [Tiene un servicio de configuración](https://www.usenix.org/system/files/1309_09-13_zamboni.pdf ) llamado [CFEngine Design Center](https://github.com/cfengine/design-center/wiki/Policies-and-Sketches ).

- [Chef](https://docs.chef.io )

> The two most important things to make a configuration management system easy to use are consistency in how you utilize it and environmental awareness. My opinion is that Ansible fails on both counts. It’s not really a full management system, but rather a more powerful administrative scripting framework with tooling to allow remote command execution.
>
> Once you narrow the pool to those three which use agent-based systems, the next most important thing for ease of use is quality and flexibility of the tooling. Chef wins this handily, it’s hardly even a contest. I much prefer writing in Python to Ruby, but the tooling around Chef is so great that I not only love it but heartily recommend it to others.
>
> https://www.quora.com/Which-is-better-for-automation-Ansible-Chef-or-Puppet

- [Ansible](https://www.ansible.com/resources/get-started ), es la opción que promueve RedHat, tiene un [repositorio de configuraciones listas para usarse](https://galaxy.ansible.com/ ), [tutoriales en línea](https://codereviewvideos.com/course/ansible-tutorial/video/ansible-inventory-with-our-own-hosts-files ) y [un sistema para evitar guardar las contraseñas](https://docs.ansible.com/ansible/latest/user_guide/vault.html ).

> There are many other orchestration tools (some even specifically for Docker), but none of them come close to Ansible's simplicity, low learning curve, and power.
>
> https://hvops.com/articles/docker-misconceptions/

- [Puppet](https://puppet.com/# )

[Es buena práctica elegir el sistema más simple que puede resolver el problema](https://hvops.com/articles/boring-systems-build-badass-businesses/ )

**Comment by AlejandraGalindoC** [comment]
Los sistemas de aprovisionamiento (#8) suelen utilizar su propio sistema de gestión de configuración y sería apropiado seleccionarlos juntos.
