### ISSUE TITLE
Recopilar manuales de soporte de los equipos

### ISSUE THREAD

**Issue by xihh87** [xihh87/cluster#62]
En el [inventario de equipos](https://docs.google.com/spreadsheets/d/1lcEfaBpBaxbph1b3tyBhJR4_lqlKWNwApUAsPJzhFuc/edit#gid=1937076125) están listados los modelos de equipos del clúster.

Por favor buscar los manuales y descargarlos en [este directorio](https://drive.google.com/drive/u/0/folders/1B1hCus-UfiFFBxSc_KPChDvNpw1tb3Nn), cada uno con el nombre: Marca - Modelo.pdf (p.e. HP - Proliant ML350 Gen9.pdf).

Muy posiblemente en el inventario está la URL de donde pueden descargarse.

**Comment by xihh87** [comment]
@AlejandraGalindoC por favor apóyame con esta solicitud.

**Comment by AlejandraGalindoC** [comment]
Los datos que se encuentran en color rojo del inventario son de equipos que no se encuentran fisicamente en el instituto

**Comment by xihh87** [comment]
Aunque visualmente es una buena herramienta, no puedo filtrar los datos por color.

Cuando tengas algún problema, agrégalo a las anotaciones.

**Comment by xihh87** [comment]
@AlejandraGalindoC por favor mueve los archivos [de este directorio](https://drive.google.com/drive/u/0/folders/1gNhnOq50Vm03shkd5m7snS4_yrz1FwpC) a su lugar correspondiente en [este otro](https://drive.google.com/drive/u/0/folders/13V2mFL5QfWC6twur2Q9tneGL0FG1RrmD)

**Comment by xihh87** [comment]
@AlejandraGalindoC muchas gracias por tu apoyo recopilando el material.

Para referencia Cisco y SMC son marcas de equipo de Red. También algunos HP son equipos de red y no tienen disco duro ni otro tipo de refacciones.
