### ISSUE TITLE
Modelo Game PC

### ISSUE THREAD

**Issue by AlejandraGalindoC** [xihh87/cluster#67]
No aparece como modelo de computadora

**Comment by AlejandraGalindoC** [comment]
No se conoce el modelo de este sistema ni manuales, ya que el proveedor no posee informacion sobre este aparato por ser del año 2008

**Comment by xihh87** [comment]
@AlejandraGalindoC, Gracias por la información, se toma en cuenta que estos equipos no tienen documentación de usuario o de soporte.
