### ISSUE TITLE
MODELO Switch SMC/8648T no se encuentra en inventario

### ISSUE THREAD

**Issue by AlejandraGalindoC** [xihh87/cluster#70]

**Comment by xihh87** [comment]
Este es un switch:

![IMG_20190610_140050948](https://user-images.githubusercontent.com/16003955/59220607-027d6c80-8b8b-11e9-9059-d9fe16087a28.jpg)

**Comment by xihh87** [comment]
@AlejandraGalindoC ese es el switch de E20. No llega hasta el frente del rack.

Por favor verifica si puedes ubicar el número de serie.
