### ISSUE TITLE
MODELO Switch IBM no se encuentra en inventario

### ISSUE THREAD

**Issue by AlejandraGalindoC** [xihh87/cluster#71]

**Comment by xihh87** [comment]
@AlejandraGalindoC  ¿A qué se refiere este problema?

**Comment by AlejandraGalindoC** [comment]
Se refiere a que no esta fisicamente en el instituto

**Comment by xihh87** [comment]
Es que es un switch, no un servidor.

![IMG_20190610_135826551](https://user-images.githubusercontent.com/16003955/59221165-458c0f80-8b8c-11e9-92f4-520149620a54.jpg)
