### ISSUE TITLE
MODELOS QUE NO SE ENCUENTRAN EN EL INVENTARIO SON: CISCO-Catalyst 2960-S, Catalyst 2960-S Series 10G, EXTREME-Summit 400-48t

### ISSUE THREAD

**Issue by AlejandraGalindoC** [xihh87/cluster#72]

**Comment by xihh87** [comment]
La mayoría de estos son  switches y no servidores.

Los próximos reportes, para evitar el aumento de tickets, agureguémolos como comentarios en el ticket asignado.
