### ISSUE TITLE
Dell1 detecta USB para instalación de Sistema Operativo, pero no es capáz de bootear desde la memoria.

### ISSUE THREAD

**Issue by MarioUlisesLopezJimenez** [xihh87/cluster#75]
@xihh87 Al tratar de instalar el sistema operativo ubuntu desde una memoria USB, el servidor es capaz de detectarla, pero no es capáz de bootear desde la misma. Arroja el error "isolinux.bin missing or corrupt"
![20190613_125638](https://user-images.githubusercontent.com/51420561/59461852-f17d6700-8de7-11e9-9246-3ad3b1778a7c.jpg)
![20190613_125701](https://user-images.githubusercontent.com/51420561/59461855-f510ee00-8de7-11e9-8bd9-95811907a372.jpg)

**Comment by MarioUlisesLopezJimenez** [comment]
Al reintentar instalar el sistema operativo desde la imagen del servidor, éste arroja un nuevo error. 
![20190613_140237](https://user-images.githubusercontent.com/51420561/59462220-e414ac80-8de8-11e9-935e-25f420b35a70.jpg)

**Comment by xihh87** [comment]
Se utilizó un CD con la imagen de ubuntu para instalar.

Se están realizando pruebas del servidor.
