### ISSUE TITLE
Especificar refacciones para servidores en centro de datos

### ISSUE THREAD

**Issue by AlejandraGalindoC** [xihh87/cluster#78]

**Comment by xihh87** [comment]
Las refacciones se agregaron [en el inventario](https://docs.google.com/spreadsheets/d/1lcEfaBpBaxbph1b3tyBhJR4_lqlKWNwApUAsPJzhFuc/edit#gid=1938462626) en las hojas «Catálogo de insumos» y «Capacidad máxima servidores».
